<?xml version="1.0" encoding="utf-8"?>
<report
	progress="">
	<activity
		result="Failed"
		duration="4.03s"
		durationms="4028"
		type="root"
		rid="16a72cbdfed7dd08"
		totalerrorcount="0"
		totalwarningcount="0"
		totalsuccesstestcasecount="0"
		totalfailedtestcasecount="0"
		totalblockedtestcasecount="0"
		childsuccesscount="0"
		childfailedcount="0"
		childblockedcount="0"
		totalsuccesscount="0"
		totalfailedcount="0"
		totalblockedcount="0"
		totalmaintenancemodecount="0"
		user="Srivi"
		rxversion="10.2.2.0"
		host="SRIVIGNESH10"
		osversion="Windows 10 64bit"
		runtimeversion="4.0.30319.42000"
		procarch="32bit"
		oslanguage="en-US"
		dtnlanguage="en-IN"
		screenresolution="1920x1080"
		timestamp="17-07-2022 14:17:29"
		timestampiso="2022-07-17T18:17:29"
		endtime="17-07-2022 14:17:33"
		timeoutfactor="1"
		runid=""
		sutversion="">
		<detail>
			Ranorex Testscript
		</detail>
		<item
			timeRelativeToTestSuiteStartTime="00:04.018"
			timeRelativeToTestModuleStartTime="00:04.018"
			timeWallClock="14:17:33"
			time="00:04.018"
			level="Failure"
			category="TestSuite">
			<message>
				Thread was being aborted.
			</message>
			<metainfo
				stacktrace="   at Microsoft.Win32.NativeMethods.ShellExecuteEx(ShellExecuteInfo info)
   at System.Diagnostics.ShellExecuteHelper.ShellExecuteFunction()
   at System.Diagnostics.ShellExecuteHelper.ShellExecuteOnSTAThread()
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Ranorex.Core.Controls.TestProgressProvider.StartTestProgressProvider(ProviderParams providerParams)
   at Ranorex.Core.Testing.TestSuiteRunner.RunInternal(Type containerType, String[] testSuiteXmls, RunParams[] rps)"
				loglvl="Failure">
			</metainfo>
		</item>
	</activity>
</report>
